#设置启用环境
spring:
  profiles:
    active: pro



---
#开发
spring:
  profiles: dev
server:
  port: 80

---
#生产
spring:
  profiles: pro
server:
  port: 81

---
#测试
spring:
  profiles: test
server:
  port: 82

---

lesson: SpringBoot

enterprise:
  name: itcast
  age: 16
  tel: 123456
  subject:
    - java
    - python
    - 大数据

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm_db
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource